version: "3.9"

services:
  mina-status-monitor:
    container_name: mina-status-monitor
    build:
      context: .
      dockerfile: Dockerfile
    image: mina-status-monitor
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "/scripts/mina-status-monitor.sh -sc ${DISABLE_SIDECAR:-FALSE} -sw ${DISABLE_SNARK_WORKER:-FALSE} -a ${SNARK_ADDRESS:-B62qnXhuoWPcUeBrqWPxPJAZ4khgd3bPdBoY1614jTzu9o9R2wJRWRo} -f ${SNARK_FEE:-0.001} -t ${TIMEZONE:-Europe/London}"
    pid: "host"
    networks:
      - mina-network

networks:
  mina-network:
    name: mina-network
    driver: bridge
